### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by Voxelstice** [nikogamer102/password-creator#1]
127.0.0.1

**Comment by nikothegamer100** [comment]
skil issue

**Comment by nikothegamer100** [comment]
nob

**Comment by Voxelstice** [comment]
No u

**Comment by nikothegamer100** [comment]
no u

**Comment by Voxelstice** [comment]
yes u

**Comment by nikothegamer100** [comment]
man

**Comment by Voxelstice** [comment]
WHAT

**Comment by Voxelstice** [comment]
HOW DO YOU EVEN-

**Comment by Voxelstice** [comment]
reporting for hacking...

**Comment by nikothegamer100** [comment]
yay i am getting reported!!!!

**Comment by Voxelstice** [comment]
banning...

**Comment by notsuu** [comment]
[Skip to content](https://github.com/nikogamer102/password-creator/issues/1#start-of-content)
Pull requests
[Issues](https://github.com/issues)
[Marketplace](https://github.com/marketplace)
[Explore](https://github.com/explore)
@notsuu
[nikogamer102](https://github.com/nikogamer102) /
[password-creator](https://github.com/nikogamer102/password-creator)
Public

Code
Issues
Pull requests 1
Actions
Projects
Wiki
Security

    Insights

Hello, #1
Closed
[Voxelstice](https://github.com/Voxelstice) opened this issue 4 hours ago · 11 comments
Closed
[Hello,](https://github.com/nikogamer102/password-creator/issues/1#)
#1
[Voxelstice](https://github.com/Voxelstice) opened this issue 4 hours ago · 11 comments
Comments
@[Voxelstice](https://github.com/Voxelstice)
Collaborator
Voxelstice commented [4 hours ago](https://github.com/nikogamer102/password-creator/issues/1#issue-1236191353)

127.0.0.1
@nikogamer102
Owner
nikogamer102 commented 4 hours ago

skil issue
@[nikogamer102](https://github.com/nikogamer102)
Owner
nikogamer102 commented [4 hours ago](https://github.com/nikogamer102/password-creator/issues/1#issuecomment-1126863453)

nob
@Voxelstice
Collaborator Author
Voxelstice commented 4 hours ago

No u
@[nikogamer102](https://github.com/nikogamer102)
Owner
nikogamer102 commented [4 hours ago](https://github.com/nikogamer102/password-creator/issues/1#issuecomment-1126863464)

no u
@Voxelstice
Collaborator Author
Voxelstice commented 4 hours ago •

yes u
@nikogamer102
Owner
nikogamer102 commented 4 hours ago

man
@[Voxelstice](https://github.com/Voxelstice)
Collaborator Author
Voxelstice commented [4 hours ago](https://github.com/nikogamer102/password-creator/issues/1#issuecomment-1126863492)

WHAT
@Voxelstice
Collaborator Author
Voxelstice commented 4 hours ago

HOW DO YOU EVEN-
@Voxelstice
Collaborator Author
Voxelstice commented 4 hours ago

reporting for hacking...
@[nikogamer102](https://github.com/nikogamer102)
Owner
nikogamer102 commented [4 hours ago](https://github.com/nikogamer102/password-creator/issues/1#issuecomment-1126863506) •

yay i am getting reported!!!!
@Voxelstice
Collaborator Author
Voxelstice commented 4 hours ago

banning...
@[Voxelstice](https://github.com/Voxelstice) Voxelstice closed this [4 hours ago](https://github.com/nikogamer102/password-creator/issues/1#issuecomment-1126863518)
@notsuu
Attach files by dragging & dropping, selecting or pasting them.
Remember, contributions to this repository should follow our GitHub Community Guidelines.
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Development

No branches or pull requests
Notifications
Customize

You’re not receiving notifications from this thread.
2 participants
@[nikogamer102](https://github.com/nikogamer102)
@[Voxelstice](https://github.com/Voxelstice)

    © 2022 GitHub, Inc.

    [Terms](https://docs.github.com/en/github/site-policy/github-terms-of-service)
    [Privacy](https://docs.github.com/en/github/site-policy/github-privacy-statement)
    [Security](https://github.com/security)
    [Status](https://www.githubstatus.com/)
    [Docs](https://docs.github.com/)
    [Contact GitHub](https://support.github.com/?tags=dotcom-footer)
    [Pricing](https://github.com/pricing)
    [API](https://docs.github.com/)
    [Training](https://services.github.com/)
    [Blog](https://github.blog/)
    [About](https://github.com/about)

Loading complete
